### ISSUE TITLE
Neo-scan and Neo-tracker out of sync; Not be able to transfer token

### ISSUE THREAD

**Issue by tongcw** [CityOfZion/neo-scan#376] opened 2018-11-07 05:13 UTC
Hi. I tried to transfer my token from NEON wallet.  The transaction failed.
The token disappeared from my wallet and it has never been received at the destination wallet.

Neo-scan and Neo-tracker showed different amount of token (out of sync).

Neo-scan
https://neoscan.io/address/AXGVFLfPJPUsNTNubcPPpgHHT97RJ3twKo
Neo-tracker
https://neotracker.io/address/AXGVFLfPJPUsNTNubcPPpgHHT97RJ3twKo

Tx Hash:
c9c2cf126b9b4bb1e00b40b4aa23387fe68e3b2fcdeebd230ab2816b5b52e2de

What could I do to recover my fund?  Thank you for your help.

**Comment by adrienmo** [comment] 2018-11-07 07:54
Hello @tongcw your funds are not "lost" they just will not show up in neoscan or neon wallet. 

The problem is our notifications servers did not receive the nep5 transfer notification properly
http://notifications1.neeeo.org/v1/notifications/block/2930307
http://notifications4.neeeo.org/v1/notifications/block/2930307

(One of the server got it and not the other)

To solve the problem you can use your private key with another neo wallet, you should see your funds. I will update this issue when the notification servers are running properly again.

**Comment by tongcw** [comment] 2018-11-07 10:10
Thank you @adrienmo.   Is my understanding correct that the fund has been successfully transferred to the receiver's wallet?  I tried signing into different wallet with private key (e.g. O3) but still none of this token or transaction shown in the Tx history section.

**Comment by adrienmo** [comment] 2018-11-22 03:52
fixed with resync

**Closed by adrienmo** 2018-11-22 03:52 UTC
Labels: bug, resync
